name: Update Release PR
description: Find or create release Pull Request and update its body automatically.
inputs:
  githubToken:
    description: GitHub Token
    required: true
runs:
  using: "docker"
  image: "Dockerfile"
