name: Test auto-release-pr
on:
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./auto-release-pr
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          releasePRNumber: ${{ github.event.pull_request.number }}
          bodyTemplate: |
            差分

            {summary}

            以上
          commentTemplate: |
            diff
            {diff}
