name: Claude Issue Action

on:
  workflow_call:
    inputs:
      runs-on:
        description: 'The type of machine to run the job on'
        required: false
        type: string
        default: 'ubuntu-latest'
      model:
        description: 'The Claude model to use'
        required: false
        type: string
        default: 'global.anthropic.claude-sonnet-4-5-20250929-v1:0'
      region:
        description: 'AWS region to use'
        required: false
        type: string
        default: 'ap-northeast-1'
    secrets:
      AWS_ROLE_TO_ASSUME:
        required: true

permissions:
  actions: read
  contents: write
  pull-requests: write
  issues: write
  id-token: write

jobs:
  claude-pr:
    runs-on: ${{ inputs.runs-on }}
    timeout-minutes: 60
    env:
      AWS_REGION: ${{ inputs.region }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 1

      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ inputs.region }}

      - uses: anthropics/claude-code-action@v1
        with:
          track_progress: true
          use_bedrock: true

          additional_permissions: |
            actions: read

          claude_args: |
            --model ${{ inputs.model }}

          # Issue resolution instructions
          prompt: |
            REPO: ${{ github.repository }}
            ISSUE NUMBER: ${{ github.event.issue.number }}

            この Issue で挙げた課題について、修正対応をお願いします。対応の際は、以下のフローに沿って PR を作成してください：
            1. CLAUDE.md に記載されたコーディングガイドラインに従って修正を行ってください。
            2. 修正が完了したら、新しいブランチを切り、PR を作成してください。
            3. PR のタイトルや説明欄には、Issue 番号を明記し、何をどう修正したかを簡潔に記述してください。

            修正内容が Issue の趣旨から外れている場合や、より良い対応方針があれば、PR 上で相談してください。
            コードの品質を保つためにも、丁寧な対応をお願いします。
