name: Call and execute AWS CodeBuild
on:
  workflow_call:
    inputs:
      aws_account_id:
        required: true
        type: string
      codebuild_project_name:
        required: true
        type: string
      codebuild_buildspec:
        required: false
        type: string
        default: buildspec.yml
      platform:
        required: false
        type: string
        default: ubuntu-latest

jobs:
  execute:
    runs-on: ${{ inputs.platform }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::${{ inputs.aws_account_id }}:role/codebuild-github-actions-role
          aws-region: ap-northeast-1
          mask-aws-account-id: false
      - name: Execute CodeBuild
        uses: aws-actions/aws-codebuild-run-build@v1
        with:
          project-name: ${{ inputs.codebuild_project_name }}
          buildspec-override: ${{ inputs.codebuild_buildspec }}
