name: Call and execute AWS CodeBuild
on:
  workflow_call:
    inputs:
      aws_account_id:
        required: true
        type: string
      codebuild_project_name:
        required: true
        type: string
      codebuild_buildspec:
        required: false
        type: string
        default: buildspec.yml
      timeout_minutes:
        required: false
        type: number
        default: 10
      platform:
        required: false
        type: string
        default: ubuntu-latest

jobs:
  execute:
    runs-on: ${{ inputs.platform }}
    timeout-minutes: ${{ inputs.timeout_minutes }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 1
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@8df5847569e6427dd6c4fb1cf565c83acfa8afa7 # v6.0.0
        with:
          role-to-assume: arn:aws:iam::${{ inputs.aws_account_id }}:role/codebuild-github-actions-role
          aws-region: ap-northeast-1
          mask-aws-account-id: false
      - name: Execute CodeBuild
        uses: aws-actions/aws-codebuild-run-build@4d15a47425739ac2296ba5e7eee3bdd4bfbdd767 # v1.0.18
        with:
          project-name: ${{ inputs.codebuild_project_name }}
          buildspec-override: ${{ inputs.codebuild_buildspec }}
